### ISSUE TITLE
vertex color based on media type can not work

### ISSUE THREAD

**Issue by simon-xia** [kateto/R-Network-Visualization-Workshop#1]
```
colrs <- c("red", "gold")
V(net)$color <- colrs[V(net)$media.type]

```

I got element of `V(net)$color` is all `NA`

**Comment by kateto** [comment]
Do you mean the following lines:

colrs <- c("gray50", "tomato", "gold")
V(net)$color <- colrs[V(net)$media.type]

If you do have the media.type vertex attribute (as generated earlier in the script), this should return a color vector rather than NAs.
